services:
  - docker:dind

sec-os_hardening:
  stage: sec-package
  image: ansible/galaxy
  before_script:
    - mkdir -p ~/.ssh
    - echo "$DEPLOYMENT_SERVER_SSH_PRIVKEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - eval "$(ssh-agent -s)"
    - ssh-add ~/.ssh/id_rsa
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
  script:
    - echo "[prod]" >> inventory.ini
    - echo "$DEPLOYMENT_SERVER" >> inventory.ini
    - export ANSIBLE_STDOUT_CALLBACK=json
    - ansible-galaxy install dev-sec.os-hardening
    - ansible-playbook -i inventory.ini ansible-hardening.yml > sec-os_hardening-results.json
  artifacts:
    paths: [sec-os_hardening-results.json]
    when: always
    expire_in: one week
  allow_failure: true