---
name: Github - Tag commit for deployment
on:
  push:
    branches: [master]
    paths-ignore: [.github/**, "*.md"]
permissions:
  contents: read
jobs:
  pre_deployment_checks:
    if: github.repository_owner == 'apcj-f5'
    permissions:
      contents: write # for Git to git push
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@5c7944e73c4c2a096b17a9cb74d65b6c2bbafbde # v2.9.1
        with:
          egress-policy: audit
      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Run Script
        run: |
          export GITHUB_PAT=${{ secrets.GITHUB_TOKEN }}
          ${GITHUB_WORKSPACE}/.github/scripts/check-precommit.sh
      - name: Tag Commit
        run: |
          git tag --force deploy
          git push --force origin --tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
