name: "hapi.f5labs.dev - ZAP API Scan"
on:
  workflow_dispatch:
  schedule:
    - cron: "15 00 * * *"
# Declare default permissions as read only.
permissions: read-all
jobs:
  zap-api:
    name: "ZAP API Scan"
    runs-on: ubuntu-latest
    permissions:
      # Needed to write to Issues.
      issues: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          ref: master
      - name: ZAP Scan
        uses: zaproxy/action-api-scan@v0.7.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: "ghcr.io/zaproxy/zaproxy:stable"
          format: openapi
          target: tests/hapi/hapi-swagger.json
          issue_title: "hapi.f5labs.dev - OWASP ZAP API Scan"
          fail_action: "true"
          cmd_options: "-I -S"
